'use strict';

const ACTIVITY_TYPES = Object.freeze(['ride', 'product', 'buddy']);
const ACTIVITY_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  RECRUITING: 'RECRUITING',
  FORMED: 'FORMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED'
});
const APPLICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  LEFT: 'LEFT',
  EXPIRED: 'EXPIRED',
  CANCELLED_BY_ACTIVITY: 'CANCELLED_BY_ACTIVITY'
});
const MEMBER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  LEFT: 'LEFT',
  REMOVED: 'REMOVED'
});
const RIDE_FEE_TYPES = Object.freeze(['FREE', 'SHARED_COST', 'NO_COST']);
const RIDE_LUGGAGE_RULES = Object.freeze(['NO_LARGE', 'ONE_SMALL', 'TRUNK_OK']);
const PRODUCT_DELIVERY_MODES = Object.freeze(['FACE_TO_FACE', 'PICKUP', 'ARRANGE_AFTER_FORMED']);
const BUDDY_COST_MODES = Object.freeze(['AA', 'SELF_PAY', 'HOST_TREATS']);
const BUDDY_LEVELS = Object.freeze(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']);
const REPORT_REASONS = Object.freeze([
  'FALSE_INFORMATION',
  'ILLEGAL_RIDE_CHARGE',
  'FRAUD_OR_DIVERSION',
  'HARASSMENT',
  'OTHER'
]);

module.exports = {
  ACTIVITY_TYPES,
  ACTIVITY_STATUS,
  APPLICATION_STATUS,
  MEMBER_STATUS,
  RIDE_FEE_TYPES,
  RIDE_LUGGAGE_RULES,
  PRODUCT_DELIVERY_MODES,
  BUDDY_COST_MODES,
  BUDDY_LEVELS,
  REPORT_REASONS
};
